### ISSUE TITLE
Name conflict when compiling with zlib

### ISSUE THREAD

**Issue by theoractice** [ermig1979/Cpl#18]
Hi, My code uses both Synet and zlib, and there are compiling errors under VS2022. The cause is that `alloc_func` is defined both in `Cpl/Xml.h`:
```
template<class Ch = char> class MemoryPool
{
public:
    typedef void *(alloc_func)(size_t);
    typedef void (free_func)(void *); 
...
```
and `zlib/zlib.h`:
```
typedef voidpf (*alloc_func)(voidpf opaque, uInt items, uInt size);
...
```

It is common for programs to deal with both xml and zip, so in your opinion, what is the proper way to solve this conflict? thanks.

**Comment by ermig1979** [comment]
Thank you for bug report. I changed this type name.

**Comment by theoractice** [comment]
Great. My code now compiles successfully.
